/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dissertation;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import javax.swing.JButton;
import javax.swing.JLabel;

import uk.ac.sheffield.vtts.model.Constant;
import uk.ac.sheffield.vtts.model.Memory;
import uk.ac.sheffield.vtts.model.Protocol;

/**
 *
 * @author zhangyan
 */
public class JFrame_main extends javax.swing.JFrame {
    
    private Protocol protocol = new Protocol();
    private final Memory memory = new Memory();
    private List<JButton> buttons_memory = new LinkedList<JButton>();
    private List<JLabel> labels_memory = new LinkedList<JLabel>();
    /**
     * Creates new form NewJFrame
     */
    public JFrame_main() {
        initComponents();
        protocol.addMemory(new Memory());
        jButton_added_edit_constant.setName("asd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jLabel_protocol_name = new javax.swing.JLabel();
        jButton_GenerateXML = new javax.swing.JButton();
        jTextField_protocol_name = new javax.swing.JTextField();
        jLabel_memory = new javax.swing.JLabel();
        jScrollPane_memory = new javax.swing.JScrollPane();
        jPanel_memory = new javax.swing.JPanel();
        jLabel_added_constant = new javax.swing.JLabel();
        jButton_added_edit_constant = new javax.swing.JButton();
        jButton_added_edit_viarable = new javax.swing.JButton();
        jLabel_added_viarable = new javax.swing.JLabel();
        jButton_add_constant = new javax.swing.JButton();
        jButton_add_viarable = new javax.swing.JButton();
        jScrollPane_overview = new javax.swing.JScrollPane();
        jTree_overview = new javax.swing.JTree();
        jLabel_broker = new javax.swing.JLabel();
        jButton_edit_constant_binding = new javax.swing.JButton();
        jLabel_operation = new javax.swing.JLabel();
        jScrollPane_operations = new javax.swing.JScrollPane();
        jPanel_operations = new javax.swing.JPanel();
        jLabel_operation_added_operation = new javax.swing.JLabel();
        jButton_operation_added_edit = new javax.swing.JButton();
        jButton_add_operation = new javax.swing.JButton();
        jLabel_constants_constant = new javax.swing.JLabel();
        jLabel_constants_viarable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Broker@Cloud Specification Editor");

        jLabel_protocol_name.setText("Protocol Name:");

        jButton_GenerateXML.setText("Generate XML");
        jButton_GenerateXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenerateXMLActionPerformed(evt);
            }
        });

        jTextField_protocol_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_protocol_nameActionPerformed(evt);
            }
        });

        jLabel_memory.setText("Memory:");

        jScrollPane_memory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_memory.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel_added_constant.setText("Constant Name");

        jButton_added_edit_constant.setText("Edit");
        jButton_added_edit_constant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_added_edit_constantActionPerformed(evt);
            }
        });

        jButton_added_edit_viarable.setText("Edit");

        jLabel_added_viarable.setText("Viarable Name");

        javax.swing.GroupLayout jPanel_constantsLayout = new javax.swing.GroupLayout(jPanel_memory);
        jPanel_memory.setLayout(jPanel_constantsLayout);
        jPanel_constantsLayout.setHorizontalGroup(
            jPanel_constantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_constantsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel_added_constant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_added_edit_constant)
                .addGap(17, 17, 17)
                .addComponent(jLabel_added_viarable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_added_edit_viarable)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_constantsLayout.setVerticalGroup(
            jPanel_constantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_constantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_constantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel_added_constant)
//                    .addComponent(jButton_added_edit_constant)
                    .addComponent(jLabel_added_viarable)
                    .addComponent(jButton_added_edit_viarable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jScrollPane_memory.setViewportView(jPanel_memory);

        jButton_add_constant.setText("Add Constant");
        jButton_add_constant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_constantActionPerformed(evt);
            }
        });

        jButton_add_viarable.setText("Add Viarable");
        jButton_add_viarable.setMaximumSize(new java.awt.Dimension(130, 29));
        jButton_add_viarable.setMinimumSize(new java.awt.Dimension(130, 29));

        jScrollPane_overview.setViewportView(jTree_overview);

        jLabel_broker.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_broker.setText("Broker@Cloud Specification Editor");

        jButton_edit_constant_binding.setText("Edit Binding");

        jLabel_operation.setText("Operation:");

        jScrollPane_operations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_operations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_operation_added_operation.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_operation_added_operation.setText("Operation");

        jButton_operation_added_edit.setText("Edit");

        javax.swing.GroupLayout jPanel_operationsLayout = new javax.swing.GroupLayout(jPanel_operations);
        jPanel_operations.setLayout(jPanel_operationsLayout);
        jPanel_operationsLayout.setHorizontalGroup(
            jPanel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operationsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel_operation_added_operation, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton_operation_added_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel_operationsLayout.setVerticalGroup(
            jPanel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operationsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_operation_added_operation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_operation_added_edit))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jScrollPane_operations.setViewportView(jPanel_operations);

        jButton_add_operation.setText("Add Operation");
        jButton_add_operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_operationActionPerformed(evt);
            }
        });

        jLabel_constants_constant.setText("Constant");

        jLabel_constants_viarable.setText("Viarable");

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addComponent(jLabel_protocol_name)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_mainLayout.createSequentialGroup()
                                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane_operations, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_add_operation, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(194, 194, 194)))
                                .addComponent(jButton_GenerateXML, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_mainLayout.createSequentialGroup()
                                .addComponent(jTextField_protocol_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel_broker, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                                .addComponent(jLabel_constants_viarable)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                                .addComponent(jScrollPane_memory, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane_overview, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton_add_constant)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_add_viarable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_edit_constant_binding))
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_mainLayout.createSequentialGroup()
                                .addComponent(jLabel_memory)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel_constants_constant))
                            .addComponent(jLabel_operation))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_protocol_name)
                    .addComponent(jTextField_protocol_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_broker, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_memory)
                            .addComponent(jScrollPane_overview, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButton_GenerateXML, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_constants_constant)
                            .addComponent(jLabel_constants_viarable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_memory, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_add_constant)
                            .addComponent(jButton_add_viarable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit_constant_binding))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_operation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_add_operation)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    
    
    
    
    
    
    // button actions========================================================================
    private void jButton_GenerateXMLActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
     
    }                                                   

    private void jTextField_protocol_nameActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO create a protocol object and give it a name, with initializing it with memory
        this.protocol = new Protocol(jTextField_protocol_name.getText());
    	protocol.addMemory(memory);
    }                                                        

    private void jButton_add_constantActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO create a constant,save it in the memory and generate a label and edit button to edit it 
    	Constant_add_dialog constant_add_dialog = new Constant_add_dialog(memory);
    	constant_add_dialog.setLocationRelativeTo(jButton_add_constant);
    	constant_add_dialog.setVisible(true);
    	
    	
    	
    	JButton jButton = constant_add_dialog.get_generated_button();
    	JLabel jLabel = constant_add_dialog.get_generated_label();
    	jButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				jButton_added_edit_constantActionPerformed(e);
				
			}
		});
    	this.buttons_memory.add(jButton);
    	this.labels_memory.add(jLabel);
    	
    	reload_memory_panel();
    }                                                    

    private void jButton_add_operationActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jButton_added_edit_constantActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    	String constant_name = ((JButton)evt.getSource()).getName();
    	
    	// pop up edit dialog window
    	Constant_edit_dialog constant_edit_dialog = new Constant_edit_dialog(memory, constant_name);
    	constant_edit_dialog.setLocationRelativeTo(jButton_added_edit_constant);
		constant_edit_dialog.setVisible(true);
        
        
        System.out.println("finished editing constant.");
        jPanel_memory.revalidate();

    }                                                           

    
    // model modifiers======================================================================
    private void generate_constant_button() {
		Set<Constant> constants = memory.getConstants();
		for (Constant constant : constants) {
			JButton jButton = new JButton();
			jButton.setName(constant.getName());
			jButton.addActionListener(new ActionListener() {
				
				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					jButton_added_edit_constantActionPerformed(e);
				}
			});
		}
	}
    
    private void reload_memory_panel(){
    	int init_y_position = 10;
    	for (JButton jButton : buttons_memory) {
			jButton.setLocation(150, init_y_position);
    		jPanel_memory.add(jButton);
    		init_y_position = init_y_position+70;
		}
    	init_y_position = 10;
    	for (JLabel jLabel : labels_memory) {
			jLabel.setLocation(30, init_y_position);
    		jPanel_memory.add(jLabel);
    		init_y_position = init_y_position+70;
		}
    	
    	jPanel_memory.revalidate();
    	validate();
    	repaint();
    	System.out.println(buttons_memory.size());
    }
    
   
     
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_GenerateXML;
    private javax.swing.JButton jButton_add_constant;
    private javax.swing.JButton jButton_add_operation;
    private javax.swing.JButton jButton_add_viarable;
    private javax.swing.JButton jButton_added_edit_constant;
    private javax.swing.JButton jButton_added_edit_viarable;
    private javax.swing.JButton jButton_edit_constant_binding;
    private javax.swing.JButton jButton_operation_added_edit;
    private javax.swing.JLabel jLabel_added_constant;
    private javax.swing.JLabel jLabel_added_viarable;
    private javax.swing.JLabel jLabel_broker;
    private javax.swing.JLabel jLabel_constants_constant;
    private javax.swing.JLabel jLabel_constants_viarable;
    private javax.swing.JLabel jLabel_memory;
    private javax.swing.JLabel jLabel_operation;
    private javax.swing.JLabel jLabel_operation_added_operation;
    private javax.swing.JLabel jLabel_protocol_name;
    private javax.swing.JPanel jPanel_memory;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_operations;
    private javax.swing.JScrollPane jScrollPane_memory;
    private javax.swing.JScrollPane jScrollPane_operations;
    private javax.swing.JScrollPane jScrollPane_overview;
    private javax.swing.JTextField jTextField_protocol_name;
    private javax.swing.JTree jTree_overview;
    // End of variables declaration                   
}
